from test_record_methods import TestRecordMethods
from test_node_methods import TestNodeMethods
from test_graph_methods import TestGraphMethods
from test_grabber_methods import TestGrabberMethods
from test_geneagrapher_methods import TestGeneagrapherMethods
